In [1]:
#Matematiksel İşlemler

In [2]:
import numpy as np

In [3]:
v = np.array([1,2,3,4,5])

In [4]:
v - 1 

array([0, 1, 2, 3, 4])

In [5]:
v * 5

array([ 5, 10, 15, 20, 25])

In [6]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [7]:
v*5/10 - 1

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [8]:
#ufunc

In [10]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [11]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [12]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [13]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [14]:
v**3

array([  1,   8,  27,  64, 125], dtype=int32)

In [16]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [17]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [18]:
np.mod(v, 2)

array([1, 0, 1, 0, 1], dtype=int32)

In [19]:
np.absolute(np.array([-3]))

array([3])

In [20]:
np.sin(360)

0.9589157234143065

In [21]:
np.cos(180)

-0.5984600690578581

In [22]:
v = np.array([1,2,3])

In [23]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [24]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [25]:
?np

In [26]:
#cheatsheet

İstatiksel Hesaplamalar

In [27]:
v

array([1, 2, 3])

In [28]:
np.mean(v)

2.0

In [29]:
v.sum()

6

In [30]:
v.min()

1