In [1]:
print("a")

a


In [2]:
Merhaba

NameError: name 'Merhaba' is not defined

In [3]:
"a"

'a'

#Neden Numpy


In [7]:
a = [1,2,3,4]
b = [2,3,4,5]
a


[1, 2, 3, 4]

In [6]:
b

[2, 3, 4, 5]

In [9]:
ab = []

for i in range (0, len(a)):
    ab.append(a[i]*b[i])
    
ab

[2, 6, 12, 20]

In [10]:
import numpy as np

In [11]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [12]:
a*b

array([ 2,  6, 12, 20])

#Numpay Arrayı Oluşturmak

In [13]:
import numpy as np

In [14]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [15]:
a = np.array([1,2,3,4,5])

In [16]:
type(a)

numpy.ndarray

In [18]:
np.array([3,14,4,2,13], dtype = "int")

array([ 3, 14,  4,  2, 13])

#sıfırdan array oluşturma

In [19]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.full([3,5],3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [22]:
np.arange(0,31,3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [23]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [24]:
np.random.normal(10,4, (3,4))

array([[ 8.51713828,  9.45059416,  8.75795691, 11.32800406],
       [14.5880721 , 14.21144806, 11.72378854,  3.19974251],
       [11.79657326, 10.92301564,  8.20325662,  7.99093509]])

In [25]:
np.random.randint(0,10, (3,4))

array([[1, 5, 4, 3],
       [7, 9, 2, 1],
       [6, 6, 0, 3]])

NumPy Array Özellikler

In [1]:
import numpy as np

In [2]:
np.random.randint(10, size = 10)

array([4, 4, 1, 2, 3, 4, 9, 9, 6, 1])

In [3]:
a = np.random.randint(10,size = 10)

In [4]:
a.ndim

1

In [5]:
a.shape

(10,)

In [6]:
a.size

10

In [7]:
a.dtype

dtype('int32')

In [8]:
b =np.random.randint(10, size = (3,5))

In [9]:
b

array([[7, 9, 8, 1, 5],
       [0, 9, 3, 6, 7],
       [5, 6, 1, 9, 7]])

In [10]:
b.ndim

2

In [11]:
b.shape

(3, 5)

In [12]:
b.size

15

In [13]:
b.dtype

dtype('int32')

In [14]:
import numpy as np

In [15]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a = np.arange(1,10)

In [18]:
a.ndim

1

In [19]:
 a.reshape((1,9))

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [20]:
b = a.reshape((1,9))

In [21]:
b.ndim

2

ARRAY BİRLEŞTİRM(CONCATENATİON)

In [22]:
import numpy as np

In [23]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [24]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [25]:
z = np.array([7,8,9])

In [28]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#İki Boyut

In [32]:
a = np.array([[1,2,3],[4,5,6]])

In [33]:
np.concatenate([a,a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [34]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Array Ayırma (Splitting)

In [35]:
import numpy as np

In [36]:
x = np.array([1,2,3,99,99,3,2,1])

In [37]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [38]:
a,b,c = np.split(x, [3,5])

In [39]:
a

array([1, 2, 3])

In [40]:
b

array([99, 99])

In [41]:
c

array([3, 2, 1])

In [42]:
#İki Boyutlu Ayırma

In [43]:
m = np.arange(16).reshape(4,4)

In [44]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
np.vsplit(m , [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [46]:
ust, alt = np.vsplit(m, [2])

In [47]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [48]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [50]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [51]:
sag,sol = np.hsplit(m, [2])

In [52]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [53]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

Array Sıralama(Sorting)

In [54]:
import numpy as np

In [55]:
v = np.array([2,1,4,3,5])

In [56]:
v

array([2, 1, 4, 3, 5])

In [57]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [58]:
v

array([2, 1, 4, 3, 5])

In [59]:
v.sort()

In [60]:
v

array([1, 2, 3, 4, 5])

In [61]:
#İki Boyutlu Array Sıralama

In [63]:
m = np.random.normal(20,5, (3,3))

In [64]:
m

array([[18.12460509, 18.47119224, 16.92963164],
       [28.02772995,  7.90502654,  6.91477786],
       [31.83931712, 19.71989914, 33.9272847 ]])

In [65]:
np.sort(m, axis = 1)

array([[16.92963164, 18.12460509, 18.47119224],
       [ 6.91477786,  7.90502654, 28.02772995],
       [19.71989914, 31.83931712, 33.9272847 ]])

In [66]:
np.sort(m, axis = 0)

array([[18.12460509,  7.90502654,  6.91477786],
       [28.02772995, 18.47119224, 16.92963164],
       [31.83931712, 19.71989914, 33.9272847 ]])

In [1]:
#Index İle Elemana Erişmek

In [2]:
import numpy as np

In [3]:
a = np.random.randint(10, size = 10)
a

array([3, 6, 5, 0, 6, 9, 2, 8, 0, 6])

In [4]:
a[0]

3

In [5]:
a[-1]

6

In [6]:
a[0] = 1

In [7]:
a

array([1, 6, 5, 0, 6, 9, 2, 8, 0, 6])

In [8]:
m = np.random.randint(10, size = (3,5))
m

array([[2, 9, 7, 4, 1],
       [4, 9, 9, 1, 5],
       [8, 3, 4, 8, 8]])

In [9]:
m[0,0]

2

In [10]:
m[1,1]

9

In [11]:
m[1,4]

5

In [12]:
m[1,4] =99

In [13]:
m

array([[ 2,  9,  7,  4,  1],
       [ 4,  9,  9,  1, 99],
       [ 8,  3,  4,  8,  8]])

In [14]:
m[1,4] = 2.2
m

array([[2, 9, 7, 4, 1],
       [4, 9, 9, 1, 2],
       [8, 3, 4, 8, 8]])

In [15]:
#Slicing İle Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [16]:
import numpy as np

In [17]:
a = np.arange(20,30) 
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [18]:
a[0:3]

array([20, 21, 22])

In [19]:
a[:3]

array([20, 21, 22])

In [20]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [21]:
a[1::2]

array([21, 23, 25, 27, 29])

In [22]:
a[0::2]

array([20, 22, 24, 26, 28])

In [23]:
# İki Boyutlu Slice İşlemleri

In [24]:
m = np.random.randint(10, size = (5,5))

In [25]:
m

array([[4, 5, 6, 5, 5],
       [2, 6, 6, 5, 3],
       [4, 0, 1, 3, 1],
       [4, 0, 4, 5, 1],
       [8, 8, 4, 6, 0]])

In [26]:
m[:,0]

array([4, 2, 4, 4, 8])

In [27]:
m[:,1]

array([5, 6, 0, 0, 8])

In [28]:
m[:,4]

array([5, 3, 1, 1, 0])

In [29]:
m[0,:]

array([4, 5, 6, 5, 5])

In [30]:
m[0]

array([4, 5, 6, 5, 5])

In [31]:
m[1,:]

array([2, 6, 6, 5, 3])

In [32]:
m[0:2, 0:3]

array([[4, 5, 6],
       [2, 6, 6]])

In [33]:
m[::,:2]

array([[4, 5],
       [2, 6],
       [4, 0],
       [4, 0],
       [8, 8]])

In [34]:
m[:,0:2]

array([[4, 5],
       [2, 6],
       [4, 0],
       [4, 0],
       [8, 8]])

In [36]:
m[1:3, 0:2]

array([[2, 6],
       [4, 0]])

In [37]:
#Alt Küme Üzerinde İşlem Yapmak

In [38]:
import numpy as np

In [39]:
a = np.random.randint(10, size = (5,5))
a

array([[8, 0, 2, 8, 0],
       [6, 5, 5, 9, 3],
       [2, 8, 3, 0, 4],
       [1, 1, 0, 3, 2],
       [4, 6, 7, 1, 4]])

In [40]:
alt_a = a[0:3, 0:2]
alt_a

array([[8, 0],
       [6, 5],
       [2, 8]])

In [41]:
alt_a[0,0] = 99999
alt_a[1,1] = 888

In [42]:
alt_a

array([[99999,     0],
       [    6,   888],
       [    2,     8]])

In [43]:
a

array([[99999,     0,     2,     8,     0],
       [    6,   888,     5,     9,     3],
       [    2,     8,     3,     0,     4],
       [    1,     1,     0,     3,     2],
       [    4,     6,     7,     1,     4]])

In [44]:
m = np.random.randint(10, size = (5,5))
m

array([[3, 3, 4, 2, 1],
       [6, 0, 8, 9, 0],
       [4, 6, 5, 4, 1],
       [0, 9, 8, 2, 4],
       [0, 6, 0, 8, 6]])

In [45]:
alt_b = m[0:3, 0:2].copy()
alt_b

array([[3, 3],
       [6, 0],
       [4, 6]])

In [46]:
alt_b[0,0] = 99999

In [47]:
alt_b

array([[99999,     3],
       [    6,     0],
       [    4,     6]])

In [48]:
m

array([[3, 3, 4, 2, 1],
       [6, 0, 8, 9, 0],
       [4, 6, 5, 4, 1],
       [0, 9, 8, 2, 4],
       [0, 6, 0, 8, 6]])

In [49]:
#Fncy Index İle Elemanlara Erişmek


In [50]:
import numpy as np

In [51]:
v = np.arange(0, 30, 3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [52]:
v[1]

3

In [53]:
v[3]

9

In [54]:
v[5]

15

In [56]:
(v[1],v[3], v[5])

(3, 9, 15)

In [57]:
al_getir = [1,3,5]

In [58]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [59]:
v[al_getir]

array([ 3,  9, 15])

In [60]:
#İki Boyutlu Fancy

In [61]:
m = np.arange(9).reshape((3,3))

In [62]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
satir = np.array([0,1])
sutun = np.array([1,2])

In [64]:
m[satir, sutun]

array([1, 5])

In [65]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
m[0, [1,2]]

array([1, 2])

In [67]:
#slice

In [68]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [69]:
#slice ile fancy

In [70]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [71]:
#Koşullu Eleman İşlemleri

In [72]:
import numpy as np
v = np.array([1,2,3,4,5])

In [73]:
v < 3

array([ True,  True, False, False, False])

In [74]:
v[v < 3]

array([1, 2])

In [75]:
v[v > 3]

array([4, 5])

In [76]:
v[v >= 3]

array([3, 4, 5])

In [77]:
v[v <= 3]

array([1, 2, 3])

In [78]:
v[v == 3]

array([3])

In [79]:
v[v != 3]

array([1, 2, 4, 5])

In [80]:
v * 2

array([ 2,  4,  6,  8, 10])

In [81]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [82]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])